server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/denglu_sp?serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/denglu_sp?serverTimezone=UTC
    username: root
    password: QWE12345
#热部署生效
spring.devtools.restart.enabled: true
